import {getFirestore,collection,getDocs} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
import {app} from "./firebase-config.js";
const db=getFirestore(app),$=id=>document.getElementById(id),key="cg_time_machine_v2";
let state=JSON.parse(localStorage.getItem(key)||"{}"),current=null,answered=false;
state={xp:0,solved:0,streak:0,lastDay:"",vault:[],mode:"mix",...state};
const problems=[
{id:"a1",level:"school",topic:"algebra",difficulty:2,q:"\\[\\boxed{\\text{If }x+\\frac1x=3,\\text{ find }x^2+\\frac1{x^2}.}\\]",a:"7",h:"Square the relation: \\[x^2+2+\\frac1{x^2}=9.\\]",s:"\\[x^2+\\frac1{x^2}=(x+\\tfrac1x)^2-2=\\boxed7.\\]"},
{id:"a2",level:"school",topic:"number theory",difficulty:3,q:"\\[\\boxed{\\gcd(2^{100}-1,2^{60}-1)=?}\\]",a:"1048575",h:"Use gcd(a^m−1,a^n−1)=a^{gcd(m,n)}−1.",s:"\\[\\gcd(100,60)=20,\\qquad2^{20}-1=\\boxed{1048575}.\\]"},
{id:"a3",level:"school",topic:"algebra",difficulty:3,q:"\\[\\text{Find the remainder when }x^{100}\\text{ is divided by }x^2-1.\\]",a:"1",h:"\\[x^2\\equiv1\\pmod{x^2-1}.\\]",s:"\\[x^{100}=(x^2)^{50}\\equiv1^{50}=\\boxed1\\pmod{x^2-1}.\\]"},
{id:"a4",level:"school",topic:"inequality",difficulty:2,q:"\\[\\boxed{\\min_{x>0}(x+\\frac1x)=?}\\]",a:"2",h:"\\[x+\\frac1x-2=\\frac{(x-1)^2}{x}.\\]",s:"\\[x+\\frac1x\\ge2,\\text{ with equality at }x=1.\\quad\\boxed2\\]"},
{id:"a5",level:"school",topic:"sequences",difficulty:3,q:"\\[\\boxed{\\sum_{k=1}^{10}\\frac1{k(k+1)}=?}\\]",a:"10/11",h:"\\[\\frac1{k(k+1)}=\\frac1k-\\frac1{k+1}.\\]",s:"\\[\\sum_{k=1}^{10}(\\frac1k-\\frac1{k+1})=1-\\frac1{11}=\\boxed{\\frac{10}{11}}.\\]"},
{id:"a6",level:"school",topic:"combinatorics",difficulty:3,q:"\\[\\text{How many subsets of }\\{1,\\ldots,10\\}\\text{ contain exactly three elements?}\\]",a:"120",h:"Choose the three elements; order does not matter.",s:"\\[\\binom{10}{3}=\\boxed{120}.\\]"},
{id:"c1",level:"school",topic:"calculus",difficulty:3,q:"\\[\\boxed{\\int_0^1\\frac{2x}{1+x^2}\\,dx=?}\\]",a:"ln2",h:"Set \\(u=1+x^2\\).",s:"\\[\\int_0^1\\frac{2x}{1+x^2}dx=\\left[\\ln(1+x^2)\\right]_0^1=\\boxed{\\ln2}.\\]"},
{id:"c2",level:"university",topic:"calculus",difficulty:4,q:"\\[\\boxed{\\lim_{x\\to0}\\frac{\\sin x-x}{x^3}=?}\\]",a:"-1/6",h:"Use \\(\\sin x=x-\\frac{x^3}{6}+O(x^5)\\).",s:"\\[\\sin x-x=-\\frac{x^3}{6}+O(x^5),\\quad\\boxed{-\\frac16}.\\]"},
{id:"c3",level:"university",topic:"calculus",difficulty:3,q:"\\[\\text{For }f(x)=x^x,\\text{ find }f'(1).\\]",a:"1",h:"Write \\(x^x=e^{x\\ln x}\\).",s:"\\[f'(x)=x^x(\\ln x+1),\\qquad f'(1)=\\boxed1.\\]"},
{id:"c4",level:"university",topic:"calculus",difficulty:4,q:"\\[\\boxed{\\int_0^1\\ln(1+x)\\,dx=?}\\]",a:"2ln2-1",h:"An antiderivative is \\((1+x)\\ln(1+x)-(1+x)\\).",s:"\\[\\int_0^1\\ln(1+x)dx=\\boxed{2\\ln2-1}.\\]"},
{id:"c5",level:"university",topic:"series",difficulty:4,q:"\\[\\boxed{\\sum_{n=1}^{\\infty}\\frac1{n(n+1)(n+2)}=?}\\]",a:"1/4",h:"\\[\\frac1{n(n+1)(n+2)}=\\frac12(\\frac1{n(n+1)}-\\frac1{(n+1)(n+2)}).\\]",s:"The series telescopes to \\(\\boxed{\\frac14}\\)."},
{id:"c6",level:"university",topic:"number theory",difficulty:5,q:"\\[\\boxed{\\text{Find the least positive }n\\text{ such that }2^n\\equiv1\\pmod{31}.}\\]",a:"5",h:"Fermat gives 2^30 ≡ 1. Test the proper divisors of 30.",s:"\\[2^5=32\\equiv1\\pmod{31},\\quad\\boxed5.\\]"},
{id:"h1",level:"university",topic:"analysis",difficulty:5,q:"\\[f(x)=x^2\\sin(1/x)\\ (x\\ne0),\\quad f(0)=0.\\text{ Find }f'(0).\\]",a:"0",h:"\\[f'(0)=\\lim_{h\\to0}h\\sin(1/h).\\]",s:"\\[|h\\sin(1/h)|\\le|h|\\to0,\\quad\\boxed{f'(0)=0}.\\]"},
{id:"h2",level:"university",topic:"linear algebra",difficulty:5,q:"\\[\\text{A }2\\times2\\text{ matrix has eigenvalues }2,5.\\text{ Find }\\operatorname{tr}(A^2).\\]",a:"29",h:"The eigenvalues of A² are 4 and 25.",s:"\\[\\operatorname{tr}(A^2)=2^2+5^2=\\boxed{29}.\\]"},
{id:"h3",level:"university",topic:"complex numbers",difficulty:5,q:"\\[\\boxed{\\left|\\frac{1+i}{1-i}\\right|=?}\\]",a:"1",h:"Use \\(|z/w|=|z|/|w|\\).",s:"\\[\\left|\\frac{1+i}{1-i}\\right|=\\frac{\\sqrt2}{\\sqrt2}=\\boxed1.\\]"},
{id:"h4",level:"university",topic:"integrals",difficulty:5,q:"\\[\\boxed{\\int_0^{\\pi/2}\\sin^3x\\,dx=?}\\]",a:"2/3",h:"\\[\\sin^3x=\\sin x(1-\\cos^2x).\\]",s:"\\[\\int_0^{\\pi/2}\\sin^3x\\,dx=\\int_0^1(1-u^2)du=\\boxed{\\frac23}.\\]"}
];
function save(){localStorage.setItem(key,JSON.stringify(state));stats()}
function stats(){$("tmXp").textContent=state.xp;$("tmSolved").textContent=state.solved;$("tmStreak").textContent=state.streak;$("tmVault").textContent=state.vault.length}
function today(){return new Date().toISOString().slice(0,10)}
function streak(){let t=today();if(state.lastDay!==t){let d=new Date();d.setDate(d.getDate()-1);state.streak=state.lastDay===d.toISOString().slice(0,10)?state.streak+1:1;state.lastDay=t}}
function pool(){return problems.filter(p=>state.mode==="mix"||(state.mode==="hard"&&p.difficulty>=4)||p.level===state.mode)}
function stars(n){return"★".repeat(n)+"☆".repeat(5-n)}
function math(el){if(window.MathJax)MathJax.typesetPromise([el]).catch(()=>{})}
function load(p){current=p||pool()[Math.floor(Math.random()*pool().length)];answered=false;$("tmProblem").innerHTML=current.q;$("tmEra").textContent="Present · Challenge #"+String(problems.indexOf(current)+1).padStart(3,"0");$("tmDifficulty").textContent="DIFFICULTY · "+stars(current.difficulty);$("tmLevel").textContent=current.level.toUpperCase();$("tmTopic").textContent=current.topic.toUpperCase();$("tmType").textContent=current.difficulty>=4?"DEEP DIVE":"CHALLENGE";$("tmAnswer").value="";$("tmFeedback").textContent="";$("tmFeedback").className="tm-feedback";$("tmHintBox").className="tm-hint";$("tmSolutionBox").className="tm-solution";$("tmProgress").style.width=current.difficulty*20+"%";math($("tmProblem"))}
function norm(s){return String(s).toLowerCase().trim().replace(/[{}\\\s]/g,"")}
function check(){if(answered)return;let g=norm($("tmAnswer").value),a=norm(current.a);if(!g){$("tmFeedback").textContent="Enter an answer first.";return}if(g===a){answered=true;streak();state.solved++;state.xp+=10+current.difficulty*5;save();$("tmFeedback").textContent="Correct. +"+(10+current.difficulty*5)+" XP";$("tmFeedback").className="tm-feedback good"}else{$("tmFeedback").textContent="Not quite. Try another line of reasoning.";$("tmFeedback").className="tm-feedback bad"}}
function spend(n){if(state.xp<n){$("tmFeedback").textContent="You need "+(n-state.xp)+" more XP for that.";return false}state.xp-=n;save();return true}
function vault(){let e=$("tmVaultList");if(!state.vault.length){e.innerHTML='<div class="tm-empty">Solve something worth keeping. Your saved problems will appear here.</div>';return}e.innerHTML=state.vault.map((p,i)=>'<article class="tm-vault-item"><div class="vmeta"><span>#'+(i+1)+'</span><span>'+p.topic+'</span><span>'+stars(p.difficulty)+'</span></div><div>'+p.q+'</div></article>').join("");math(e)}
$("tmSubmit").onclick=check;$("tmAnswer").onkeydown=e=>{if(e.key==="Enter")check()};$("tmNext").onclick=()=>load();$("tmHint").onclick=()=>{if(spend(10)){$("tmHintBox").innerHTML=current.h;$("tmHintBox").classList.add("open");math($("tmHintBox"))}};$("tmSolution").onclick=()=>{if(spend(30)){$("tmSolutionBox").innerHTML=current.s;$("tmSolutionBox").classList.add("open");math($("tmSolutionBox"))}};$("tmVaultBtn").onclick=()=>{if(state.vault.some(x=>x.id===current.id))return;$("tmFeedback").textContent="Saved to your vault.";state.vault.push(current);save();vault()};$("tmClearVault").onclick=()=>{state.vault=[];save();vault()};
document.querySelectorAll(".tm-mode").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tm-mode").forEach(x=>x.classList.remove("active"));b.classList.add("active");state.mode=b.dataset.mode;save();load()});
async function archive(){let c=$("allSumsContainer"),buttons=document.querySelectorAll(".tm-filter"),sources=[["s-daily.html","daily","school","schoolDailyProblem"],["u-daily.html","daily","university","universityDailyProblem"],["s-weekly.html","weekly","school","schoolWeeklyProblem"],["u-weekly.html","weekly","university","universityWeeklyProblem"]],all=[];let live=(await Promise.all(sources.map(async s=>{try{let r=await fetch(s[0],{cache:"no-store"}),d=new DOMParser().parseFromString(await r.text(),"text/html"),p=d.getElementById(s[3]),dt=d.querySelector(".challenge-date");return p?{type:s[1],level:s[2],date:dt?.textContent.trim()||"",problem:p.innerHTML.trim(),current:true}:null}catch{return null}}))).filter(Boolean);let old=[];try{old=(await getDocs(collection(db,"challengeArchive"))).docs.map(d=>({id:d.id,...d.data()}))}catch{}let seen=new Set;live.concat(old).forEach(p=>{let k=[p.level,p.type,p.date,p.problem].join("|");if(!seen.has(k)){seen.add(k);all.push(p)}});function draw(f){let a=f==="all"?all:all.filter(p=>p.type===f||p.level===f);c.innerHTML=a.length?a.map(p=>'<article class="archive-sum-card"><div class="archive-sum-meta"><span>'+esc(p.level)+'</span><span>'+esc(p.type)+'</span><span>'+esc(p.date)+'</span></div><div class="archive-sum-problem">'+p.problem+"</div></article>").join(""):'<div class="archive-status">No published sums found for this route.</div>';math(c)}buttons.forEach(b=>b.onclick=()=>{buttons.forEach(x=>x.classList.remove("active"));b.classList.add("active");draw(b.dataset.filter)});draw("all")}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
stats();vault();load();archive();